### ISSUE TITLE
Estree AST or SWC AST

### ISSUE THREAD

**Issue by qwertydelle** [pintariching/rustle#54]
Ok so we might have a problem the AST `swc_ecma_parser` produces is very different from the EStree compatible AST that `acorn` uses.  The `swc_estree_compat` library provides a way to transform SWC AST to an EStree compatible AST but it makes overall parsing much slower than just using the SWC AST and it also requires the nightly compiler which is unstable. Should we use the nightly compiler and risk some features being removed, build our own AST transformer or just use the SWC AST?

**Comment by qwertydelle** [comment]
Using the SWC AST is what I think is the right path but I want to see what other people think.

**Comment by pintariching** [comment]
If we're using SWC for code generation, then it would be better to use their AST I think. There are some custom nodes that Svelte uses, but these are used for compiling the JS AST. I've used the Estree AST as it was similar to the one Svelte uses. 
I also think switching to the SWC AST would be a good call.

**Comment by HerringtonDarkholme** [comment]
SWC is the de-facto JavaScript transpiler in the Rust world and I would highly recommend to use it for non-trivial code generation. SWC itself lacks good documentation support (back then I investigated it) and using another layer of translation might worsen the lack of docs.

Other alternatives like rslint is less supported, sadly.

**Comment by qwertydelle** [comment]
@HerringtonDarkholme have you found any good alternatives to `Visitor/VistorMut` while working on Rusty Vue?

**Comment by HerringtonDarkholme** [comment]
Rusty Vue uses totally different strategy though. It is more like "find and catch" game:
find AST node with certain pattern and replace their text content. 

For example, in https://github.com/vuejs/core/blob/main/packages/reactivity-transform/src/reactivityTransform.ts#L472
`{ foo }` is transpiled to `{ prop: __props_prop }`. The rewrite is implemented in string manipulation based on magic-string.

This approach is more performant (only need parsing) and easy (Visitor pattern is quite pedantic I would say). 
The cons is that it might not be composable because different rewriting cannot be applied at the same time. So things like transpiling ES6 to ES5 is hard for such approach.

Whether it is good approach depends on svelte's compilation output.

**Comment by pintariching** [comment]
I implemented my own walker to walk through the AST and get all the values that will update. Check out `src::compiler::analyse::extract_variables_that_change`. Now I can generate a `.js` file but I need to work on getting reactivity working. Check out the `rustle::tests` folder.

**Comment by pintariching** [comment]
That sounds exactly like something I was looking for. Does it work with the `swc_ecma_ast`? I need something that looks through an AST and finds all the variables that will change for example `UpdateExpr`. Then to make the output reactive, it needs to change a function like 
```
let counter = 0
const increment = () => counter++ 
```
into something like
```
let counter = 0
const increment = () => { counter++; lifecycle.update(["counter"]) };
```

**Comment by HerringtonDarkholme** [comment]
I tried it with ast-grep YAML.

The result is something like below:
<img width="729" alt="image" src="https://user-images.githubusercontent.com/2883231/192600886-d7e542be-cad9-4669-8fe2-bde9efea679b.png">

With this rule:

```yaml
rule:
  all:
    - pattern: $B
    - any:
        - pattern: $A++
        - pattern: $A--
        - pattern: ++$A
        - pattern: --$A
        - pattern: $A = $
        - pattern: $A += $
        - pattern: $A -= $
fix: ($B, lifecycle.update(["$A"]))

```

**Comment by HerringtonDarkholme** [comment]
I have implemented playground support for trying ast-grep! See the above example in the following link

https://ast-grep.github.io/playground.html#eyJtb2RlIjoiQ29uZmlnIiwibGFuZyI6InR5cGVzY3JpcHQiLCJxdWVyeSI6ImNvbnNvbGUubG9nKCRNQVRDSCkiLCJjb25maWciOiJydWxlOlxuICBhbGw6XG4gICAgLSBwYXR0ZXJuOiAkQlxuICAgIC0gYW55OlxuICAgICAgICAtIHBhdHRlcm46ICRBKytcbiAgICAgICAgLSBwYXR0ZXJuOiAkQS0tXG4gICAgICAgIC0gcGF0dGVybjogKyskQVxuICAgICAgICAtIHBhdHRlcm46IC0tJEFcbiAgICAgICAgLSBwYXR0ZXJuOiAkQSA9ICRcbiAgICAgICAgLSBwYXR0ZXJuOiAkQSArPSAkXG4gICAgICAgIC0gcGF0dGVybjogJEEgLT0gJFxuZml4OiAoJEIsIGxpZmVjeWNsZS51cGRhdGUoWyckQSddKSkiLCJzb3VyY2UiOiJsZXQgY291bnRlciA9IDA7XG5jb25zdCBpbmNyZW1lbnQgPSAoKSA9PiBjb3VudGVyKys7In0

**Comment by pintariching** [comment]
Sorry for the late response, I've been quite busy with other stuff. The playground looks awesome, thanks for the example! I'll look into ast-grep to see if/how we could use it in rustle!

**Comment by pintariching** [comment]
For now I've implemented a custom AST walker for the `swc_ecma_ast` which we should use instead of `swc_estree_ast`. I want the project to use the least amount of dependencies as it's possible. Maybe in the future we'll maybe need to use `ast-grep` if we're going to need more complex transformations.
